// aray: store multiple value in single variable ( index start with ==  0)

let arr=[11,22,33,44,55]
console.log(arr);
console.log(arr[3])

// push method : insert into last index...

// pop method : remove from last  index...

// shift method : remove frome first index....

// unshift method : insert into first index...

// splice method : any position remove or added element....

